# Generated by Django 5.2.1 on 2025-05-20 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('gtin_ean', models.CharField(blank=True, max_length=255)),
                ('width', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=100)),
                ('depth', models.CharField(blank=True, max_length=100)),
                ('mark', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('url_external_images', models.TextField(blank=True)),
                ('product_category', models.CharField(blank=True, max_length=255)),
                ('additional_information', models.TextField(blank=True)),
                ('ano_de_publicacao', models.CharField(blank=True, max_length=4)),
                ('page_of_number', models.CharField(blank=True, max_length=10)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('isbn10', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
