# Generated by Django 5.2.1 on 2025-05-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn10',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
