# Generated by Django 5.2.1 on 2025-05-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_isbn_book_stock_remove_book_isbn10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ano_de_publicacao',
            new_name='year_published',
        ),
    ]
