# Generated by Django 5.2.1 on 2025-05-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
