# Generated by Django 5.2.1 on 2025-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id_bling',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
