# Generated by Django 5.2.1 on 2025-06-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_id_bling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='created_by',
        ),
    ]
