# Generated by Django 5.2.1 on 2025-06-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_rename_user_book_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id_bling',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
