# Generated by Django 5.1.7 on 2025-06-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_id_bling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='book',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='book',
            name='height',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='width',
        ),
    ]
