# Generated by Django 5.2.1 on 2025-06-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_book_additional_information_remove_book_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
