# Generated by Django 5.1.7 on 2025-06-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
