# Generated by Django 5.2.1 on 2025-06-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_price'),
    ]

    operations = [
    ]
