# Generated by Django 5.2.1 on 2025-06-04 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credentials',
            name='expires_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credentials',
            name='scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='token_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
