# Generated by Django 5.2.1 on 2025-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0002_credentials_created_at_credentials_expires_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='token_type',
        ),
        migrations.AddField(
            model_name='credentials',
            name='token_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='expires_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='refresh_token',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
