# Generated by Django 5.2.1 on 2025-06-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0003_remove_credentials_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlingCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=150)),
                ('client_secret', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='Credentials',
            new_name='ApiIntegrationToken',
        ),
    ]
