# Generated by Django 5.2.1 on 2025-06-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0004_blingcredential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blingcredential',
            name='deposit_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
